### ISSUE TITLE
Upload progress status

### ISSUE THREAD

**Issue by SrPatinhas** [saschazar21/node-openload#3]
Like the title suggests, would it be possible/is on the roadmap to add a progress status to the local upload method?

**Comment by saschazar21** [comment]
Hi @SrPatinhas - how would you imagine that? It would need some kind of stream to constantly emit events containing the status. I think the overall workflow of the upload function needs to be changed as well.

Do you know some kind of solution to this? It would be interesting to include such a feature in a future release. I might be doing it by myself as well, if it was necessary - however I'm missing the use case of it a little bit....

**Comment by SrPatinhas** [comment]
@saschazar21 well, GOT has this function [.on('uploadProgress', progress)](https://github.com/sindresorhus/got#onuploadprogress-progress) that we maybe could use. what we could have more problems would be on the display of the info, but nothing that we could not work out.

**Comment by saschazar21** [comment]
Hey @SrPatinhas - sorry for not getting back to you during such a long time. I had to focus on other projects in the mean time. I will tackle this issue during the next days and I'll try to keep you updated.

**Comment by SrPatinhas** [comment]
Don't worry, I have been busy with other projects as well, so, anything just say ;)

**Comment by saschazar21** [comment]
Hi @SrPatinhas - now I finally got time to implement the upload progress. It's not very pretty and I had to rewrite the upload function to a class, but it finally works.

All you have to do is to add a callback function which is able to handle [got's progress event](https://github.com/sindresorhus/got#onuploadprogress-progress) as the second function parameter (as described in the [README](https://github.com/saschazar21/node-openload#readme)).

I also added the upload progress now in one of the test functions, the output is now looking like the following:
![bildschirmfoto 2018-04-28 um 11 41 41](https://user-images.githubusercontent.com/9016897/39395108-d1dcc7de-4ada-11e8-9803-220442591ea2.png)

Hope that helps for the moment...

If this issue is resolved for you, please close it - thanks in advance!

**Comment by SrPatinhas** [comment]
@saschazar21 thanks for the help ;) as soon as I can test it I will and give you feedback

**Comment by saschazar21** [comment]
Closing now due to inactivity.
